# Numpy refresher

In [2]:
import numpy as np

In [9]:
my_list = [1,2,3]
np.array(my_list)
type(my_list)

list

In [10]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(9,11,10)

array([ 9.        ,  9.22222222,  9.44444444,  9.66666667,  9.88888889,
       10.11111111, 10.33333333, 10.55555556, 10.77777778, 11.        ])

In [24]:
np.random.randint(0,10,)

0

In [3]:
np.random.normal()

0.5396940129383744

In [10]:
np.random.seed(101)
arr = np.random.randint(0,10,20)


In [13]:
arr.max()

9

In [15]:
arr.mean()

5.05

In [17]:
arr.argmax()

3

In [23]:
arr.reshape(2,10)

array([[1, 6, 7, 9, 8, 4, 8, 5, 0, 5],
       [8, 1, 3, 8, 3, 3, 2, 8, 9, 3]])

In [26]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [30]:
mat[0,9]

9

In [32]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [36]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [43]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [45]:
#Pandas refresher

Pandas

In [52]:
import pandas as pd

In [58]:
path = '/home/nikolay/TFforDeepLearningPython/TFforDeepLearningPython/FULL-TENSORFLOW-NOTES-AND-DATA/Tensorflow-Bootcamp-master/00-Crash-Course-Basics'

In [50]:
pd.read_csv()

TypeError: parser_f() missing 1 required positional argument: 'filepath_or_buffer'