In [1]:
import numpy as np

In [9]:
my_list = [1,2,3]
np.array(my_list)
type(my_list)

list

In [10]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.linspace(9,11,10)

array([ 9.        ,  9.22222222,  9.44444444,  9.66666667,  9.88888889,
       10.11111111, 10.33333333, 10.55555556, 10.77777778, 11.        ])

In [24]:
np.random.randint(0,10,)

0

In [29]:
np.random.normal()

0.4762937168827436